"""add_missing_user_columns

Revision ID: bcb410d8a536
Revises: 
Create Date: 2025-12-19 12:35:37.764890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bcb410d8a536'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('onboarding_step', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('tier_expires_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('connected_platforms', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'connected_platforms')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'email_verified')
    op.drop_column('user', 'tier_expires_at')
    op.drop_column('user', 'tier')
    op.drop_column('user', 'onboarding_step')
    op.drop_column('user', 'onboarding_completed')
    op.drop_column('user', 'preferred_language')
    op.drop_column('user', 'timezone')
    op.drop_column('user', 'website')
    op.drop_column('user', 'bio')
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
