"""Add scheduled_for

Revision ID: f16c8d54a203
Revises: 66bf9740bdf1
Create Date: 2025-12-30 17:03:50.601105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16c8d54a203'
down_revision: Union[str, Sequence[str], None] = '66bf9740bdf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contentdraft', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contentdraft', 'scheduled_for')
    # ### end Alembic commands ###
